/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PageScrollPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var BUTTON_DEFS = [
  { mode: "top", icon: "chevrons-up", label: "Page top" },
  { mode: "up", icon: "chevron-up", label: "Page up" },
  { mode: "down", icon: "chevron-down", label: "Page down" },
  { mode: "bottom", icon: "chevrons-down", label: "Page bottom" }
];
var PAGE_OVERLAP = 60;
var DEFAULT_SETTINGS = {
  showButtons: true,
  smartHide: true,
  hoverOnly: false,
  enabledButtons: { top: true, up: true, down: true, bottom: true }
};
var PageScrollPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    /**
     * One button container per workspace root (main window + pop-outs).
     * Keyed by the WorkspaceContainer so the buttons anchor to the editor
     * area, not the whole window — they don't overlap the sidebars.
     */
    this.containers = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    for (const def of BUTTON_DEFS) {
      this.addCommand({
        id: `page-scroll-${def.mode}`,
        name: def.label,
        // No default hotkeys — bind your own in Settings → Hotkeys.
        callback: () => this.scroll(def.mode, activeDocument)
      });
    }
    this.addSettingTab(new PageScrollSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      var _a;
      this.trackContainer(this.app.workspace.rootSplit);
      const floating = this.app.workspace.floatingSplit;
      (_a = floating == null ? void 0 : floating.children) == null ? void 0 : _a.forEach((c) => this.trackContainer(c));
      this.renderAll();
    });
    this.registerEvent(
      this.app.workspace.on("window-open", (win) => {
        this.trackContainer(win);
        this.renderAll();
      })
    );
    this.registerEvent(
      this.app.workspace.on(
        "window-close",
        (win) => this.untrackContainer(win)
      )
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.updateVisibility())
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.updateVisibility())
    );
    this.registerEvent(
      this.app.workspace.on("resize", () => this.updateVisibility())
    );
  }
  onunload() {
    for (const container of this.containers.values())
      container.remove();
    this.containers.clear();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    this.settings.enabledButtons = Object.assign(
      {},
      DEFAULT_SETTINGS.enabledButtons,
      data == null ? void 0 : data.enabledButtons
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.renderAll();
  }
  // --- Window tracking ------------------------------------------------------
  trackContainer(root) {
    if (this.containers.has(root))
      return;
    const container = root.doc.body.createDiv({ cls: "pagescroll-container" });
    this.containers.set(root, container);
  }
  /**
   * Right-edge offset (px) for a window's buttons. On the main window we add
   * the width of the right sidebar so the buttons sit over the editor content
   * instead of overlapping the panel; pop-outs have no sidebar.
   */
  rightInset(root) {
    var _a, _b;
    const base = 12;
    if (root !== this.app.workspace.rootSplit)
      return base;
    const right = this.app.workspace.rightSplit;
    if (!right || right.collapsed)
      return base;
    return base + ((_b = (_a = right.containerEl) == null ? void 0 : _a.offsetWidth) != null ? _b : 0);
  }
  untrackContainer(root) {
    var _a;
    (_a = this.containers.get(root)) == null ? void 0 : _a.remove();
    this.containers.delete(root);
  }
  // --- Rendering ------------------------------------------------------------
  /** Rebuild button structure in every window, then apply visibility. */
  renderAll() {
    for (const [root, container] of this.containers) {
      this.renderButtons(root, container);
    }
    this.updateVisibility();
  }
  /** (Re)build the buttons inside one root's container from current settings. */
  renderButtons(root, container) {
    container.empty();
    if (!this.settings.showButtons)
      return;
    for (const def of BUTTON_DEFS) {
      if (!this.settings.enabledButtons[def.mode])
        continue;
      const button = container.createEl("button", {
        cls: ["pagescroll-button", "clickable-icon"],
        attr: { "aria-label": def.label, id: `${def.mode}TriskiPageBtn` }
      });
      (0, import_obsidian.setIcon)(button, def.icon);
      button.onclick = () => this.scroll(def.mode, root.doc);
    }
  }
  /** Toggle visibility classes on every root's container (cheap; event-safe). */
  updateVisibility() {
    for (const [root, container] of this.containers) {
      const hidden = !this.settings.showButtons || this.settings.smartHide && this.getScrollEl(root.doc) == null;
      container.toggleClass("pagescroll-hidden", hidden);
      container.toggleClass(
        "pagescroll-hover-only",
        this.settings.showButtons && this.settings.hoverOnly
      );
      container.style.right = `${this.rightInset(root)}px`;
    }
  }
  // --- Scrolling ------------------------------------------------------------
  /**
   * Resolve the scrollable element for the active pane within `doc`.
   * Falls back to any markdown/text pane living in that document.
   */
  getScrollEl(doc) {
    var _a, _b, _c, _d;
    const inDoc = (el) => !!el && el.ownerDocument === doc;
    let view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view || !inDoc(view.containerEl)) {
      view = null;
      for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
        if (leaf.view instanceof import_obsidian.MarkdownView && inDoc(leaf.view.containerEl)) {
          view = leaf.view;
          break;
        }
      }
    }
    if (view) {
      const internal = view;
      const el = view.getMode() === "preview" ? (_b = (_a = internal.previewMode) == null ? void 0 : _a.renderer) == null ? void 0 : _b.previewEl : (_d = (_c = internal.editMode) == null ? void 0 : _c.cm) == null ? void 0 : _d.scrollDOM;
      if (el)
        return el;
    }
    const fileView = this.app.workspace.getActiveFileView();
    if (fileView && inDoc(fileView.containerEl)) {
      const el = fileView.containerEl.children[1];
      if (el instanceof HTMLElement)
        return el;
    }
    return null;
  }
  /** Scroll the active pane in `doc`. */
  scroll(mode, doc) {
    const scrollEl = this.getScrollEl(doc);
    if (!scrollEl)
      return;
    const page = scrollEl.clientHeight - PAGE_OVERLAP;
    switch (mode) {
      case "up":
        scrollEl.scrollBy(0, -page);
        break;
      case "down":
        scrollEl.scrollBy(0, page);
        break;
      case "top":
        scrollEl.scroll(0, 0);
        break;
      case "bottom":
        scrollEl.scroll(0, scrollEl.scrollHeight);
        break;
    }
  }
};
var PageScrollSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Show scroll buttons").setDesc(
      "Display the on-screen page-scroll buttons. Turn this off to use only the commands/hotkeys (the buttons can overlap UI from other plugins)."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showButtons).onChange(async (value) => {
        this.plugin.settings.showButtons = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Smart hide").setDesc(
      "Automatically hide the buttons when the focused pane has nothing to scroll (e.g. non-editor views), so they don't block other plugins."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.smartHide).onChange(async (value) => {
        this.plugin.settings.smartHide = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Visible on hover only").setDesc(
      "Keep the buttons faded out until you hover over them, so they stay unobtrusive."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.hoverOnly).onChange(async (value) => {
        this.plugin.settings.hoverOnly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Visible buttons").setHeading();
    containerEl.createEl("p", {
      text: "Choose which buttons appear on screen. Commands and hotkeys stay available regardless.",
      cls: "setting-item-description"
    });
    for (const def of BUTTON_DEFS) {
      new import_obsidian.Setting(containerEl).setName(def.label).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.enabledButtons[def.mode]).onChange(async (value) => {
          this.plugin.settings.enabledButtons[def.mode] = value;
          await this.plugin.saveSettings();
        })
      );
    }
  }
};
