/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PageScrollPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var BUTTON_DEFS = [
  { mode: "top", icon: "chevrons-up", label: "Page top" },
  { mode: "up", icon: "chevron-up", label: "Page up" },
  { mode: "down", icon: "chevron-down", label: "Page down" },
  { mode: "bottom", icon: "chevrons-down", label: "Page bottom" }
];
var DEFAULT_SETTINGS = {
  showButtons: true,
  smartHide: true,
  hoverOnly: false,
  enabledButtons: { top: true, up: true, down: true, bottom: true },
  scrollPercent: 90,
  separateReadingSpeed: false,
  scrollPercentReading: 90
};
var PageScrollPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    /**
     * One button container per workspace root (main window + pop-outs).
     * Keyed by the WorkspaceContainer so the buttons anchor to the editor
     * area, not the whole window — they don't overlap the sidebars.
     */
    this.containers = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    for (const def of BUTTON_DEFS) {
      this.addCommand({
        id: `page-scroll-${def.mode}`,
        name: def.label,
        // No default hotkeys — bind your own in Settings → Hotkeys.
        callback: () => this.scroll(def.mode)
      });
    }
    this.addSettingTab(new PageScrollSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      var _a;
      this.trackContainer(this.app.workspace.rootSplit);
      const floating = this.app.workspace.floatingSplit;
      (_a = floating == null ? void 0 : floating.children) == null ? void 0 : _a.forEach((c) => this.trackContainer(c));
      this.renderAll();
    });
    this.registerEvent(
      this.app.workspace.on("window-open", (win) => {
        this.trackContainer(win);
        this.renderAll();
      })
    );
    this.registerEvent(
      this.app.workspace.on(
        "window-close",
        (win) => this.untrackContainer(win)
      )
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.updateVisibility())
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.updateVisibility())
    );
    this.registerEvent(
      this.app.workspace.on("resize", () => this.updateVisibility())
    );
  }
  onunload() {
    for (const container of this.containers.values())
      container.remove();
    this.containers.clear();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    this.settings.enabledButtons = Object.assign(
      {},
      DEFAULT_SETTINGS.enabledButtons,
      data == null ? void 0 : data.enabledButtons
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.renderAll();
  }
  // --- Window tracking ------------------------------------------------------
  trackContainer(root) {
    if (this.containers.has(root))
      return;
    const container = root.doc.body.createDiv({ cls: "pagescroll-container" });
    this.containers.set(root, container);
  }
  /**
   * Right-edge offset (px) for a window's buttons. On the main window we add
   * the width of the right sidebar so the buttons sit over the editor content
   * instead of overlapping the panel; pop-outs have no sidebar.
   */
  rightInset(root) {
    var _a, _b;
    const base = 12;
    if (root !== this.app.workspace.rootSplit)
      return base;
    const right = this.app.workspace.rightSplit;
    if (!right || right.collapsed)
      return base;
    return base + ((_b = (_a = right.containerEl) == null ? void 0 : _a.offsetWidth) != null ? _b : 0);
  }
  untrackContainer(root) {
    var _a;
    (_a = this.containers.get(root)) == null ? void 0 : _a.remove();
    this.containers.delete(root);
  }
  // --- Rendering ------------------------------------------------------------
  /** Rebuild button structure in every window, then apply visibility. */
  renderAll() {
    for (const [root, container] of this.containers) {
      this.renderButtons(root, container);
    }
    this.updateVisibility();
  }
  /** (Re)build the buttons inside one root's container from current settings. */
  renderButtons(root, container) {
    container.empty();
    if (!this.settings.showButtons)
      return;
    for (const def of BUTTON_DEFS) {
      if (!this.settings.enabledButtons[def.mode])
        continue;
      const button = container.createEl("button", {
        cls: ["pagescroll-button", "clickable-icon"],
        attr: { "aria-label": def.label, id: `${def.mode}TriskiPageBtn` }
      });
      (0, import_obsidian.setIcon)(button, def.icon);
      button.onclick = () => this.scroll(def.mode, root);
    }
  }
  /** Toggle visibility classes on every root's container (cheap; event-safe). */
  updateVisibility() {
    for (const [root, container] of this.containers) {
      if (container.parentElement !== root.doc.body) {
        root.doc.body.appendChild(container);
      }
      const scrollEl = this.getScrollEl(root);
      const noOverflow = !!scrollEl && scrollEl.scrollHeight <= scrollEl.clientHeight + 1;
      const hidden = !this.settings.showButtons || scrollEl == null || this.settings.smartHide && noOverflow;
      container.toggleClass("pagescroll-hidden", hidden);
      container.toggleClass(
        "pagescroll-hover-only",
        this.settings.showButtons && this.settings.hoverOnly
      );
      container.style.right = `${this.rightInset(root)}px`;
    }
  }
  // --- Scrolling ------------------------------------------------------------
  /**
   * The Markdown view that is the *active* pane of `root` (or of the whole
   * workspace if `root` is omitted). Returns null for any other active view —
   * e.g. custom plugin editors like Stashpad — so the buttons stay hidden
   * there instead of acting on a background markdown tab.
   */
  getActiveMarkdownView(root) {
    const leaf = this.app.workspace.getMostRecentLeaf(root);
    return (leaf == null ? void 0 : leaf.view) instanceof import_obsidian.MarkdownView ? leaf.view : null;
  }
  /** Resolve the scrollable element for the active Markdown pane of `root`. */
  getScrollEl(root) {
    var _a, _b, _c, _d;
    const view = this.getActiveMarkdownView(root);
    if (!view)
      return null;
    const internal = view;
    const el = view.getMode() === "preview" ? (_b = (_a = internal.previewMode) == null ? void 0 : _a.renderer) == null ? void 0 : _b.previewEl : (_d = (_c = internal.editMode) == null ? void 0 : _c.cm) == null ? void 0 : _d.scrollDOM;
    return el != null ? el : null;
  }
  /** Page up/down distance (px) for the active pane, honoring the speed settings. */
  pageDistance(scrollEl, root) {
    var _a;
    const reading = ((_a = this.getActiveMarkdownView(root)) == null ? void 0 : _a.getMode()) === "preview";
    const percent = this.settings.separateReadingSpeed && reading ? this.settings.scrollPercentReading : this.settings.scrollPercent;
    return scrollEl.clientHeight * (percent / 100);
  }
  /** Scroll the active Markdown pane of `root` (or the workspace's active one). */
  scroll(mode, root) {
    const scrollEl = this.getScrollEl(root);
    if (!scrollEl)
      return;
    const page = this.pageDistance(scrollEl, root);
    switch (mode) {
      case "up":
        scrollEl.scrollBy(0, -page);
        break;
      case "down":
        scrollEl.scrollBy(0, page);
        break;
      case "top":
        scrollEl.scroll(0, 0);
        break;
      case "bottom":
        this.scrollToEnd(scrollEl);
        break;
    }
  }
  /**
   * Scroll to the true bottom, re-checking over the next few frames. In reading
   * mode, embeds/images render lazily and grow scrollHeight *after* the initial
   * scroll, which would otherwise leave us stuck partway (issue #2). Keep
   * nudging to the new bottom until it settles or we run out of attempts.
   */
  scrollToEnd(el, attempts = 12) {
    var _a;
    el.scroll(0, el.scrollHeight);
    if (attempts <= 0)
      return;
    const win = (_a = el.ownerDocument.defaultView) != null ? _a : window;
    win.requestAnimationFrame(() => {
      if (Math.ceil(el.scrollTop + el.clientHeight) < el.scrollHeight) {
        this.scrollToEnd(el, attempts - 1);
      }
    });
  }
};
var PageScrollSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Show scroll buttons").setDesc(
      "Display the on-screen page-scroll buttons. Turn this off to use only the commands/hotkeys (the buttons can overlap UI from other plugins)."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showButtons).onChange(async (value) => {
        this.plugin.settings.showButtons = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Smart hide").setDesc(
      "Also hide the buttons when the current note is short enough that there's nothing to scroll. (Non-editor panes \u2014 e.g. other plugins' views \u2014 always hide.)"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.smartHide).onChange(async (value) => {
        this.plugin.settings.smartHide = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Visible on hover only").setDesc(
      "Keep the buttons faded out until you hover over them, so they stay unobtrusive."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.hoverOnly).onChange(async (value) => {
        this.plugin.settings.hoverOnly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Scroll distance").setHeading();
    new import_obsidian.Setting(containerEl).setName("Page up/down distance").setDesc("How far a page up/down scrolls, as a percentage of the visible height.").addSlider(
      (slider) => slider.setLimits(20, 100, 5).setValue(this.plugin.settings.scrollPercent).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.scrollPercent = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Separate distance in Reading view").setDesc("Use a different page up/down distance when viewing in Reading mode.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.separateReadingSpeed).onChange(async (value) => {
        this.plugin.settings.separateReadingSpeed = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.separateReadingSpeed) {
      new import_obsidian.Setting(containerEl).setName("Reading view distance").setDesc("Page up/down distance used in Reading mode.").addSlider(
        (slider) => slider.setLimits(20, 100, 5).setValue(this.plugin.settings.scrollPercentReading).setDynamicTooltip().onChange(async (value) => {
          this.plugin.settings.scrollPercentReading = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Visible buttons").setHeading();
    containerEl.createEl("p", {
      text: "Choose which buttons appear on screen. Commands and hotkeys stay available regardless.",
      cls: "setting-item-description"
    });
    for (const def of BUTTON_DEFS) {
      new import_obsidian.Setting(containerEl).setName(def.label).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.enabledButtons[def.mode]).onChange(async (value) => {
          this.plugin.settings.enabledButtons[def.mode] = value;
          await this.plugin.saveSettings();
        })
      );
    }
  }
};
