/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PageScrollPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var CARET_JUMP_THRESHOLD = 10;
var MAX_CARET_HISTORY = 50;
var BUTTON_DEFS = [
  { mode: "top", icon: "chevrons-up", label: "Page top" },
  { mode: "up", icon: "chevron-up", label: "Page up" },
  { mode: "down", icon: "chevron-down", label: "Page down" },
  { mode: "bottom", icon: "chevrons-down", label: "Page bottom" }
];
var DEFAULT_SETTINGS = {
  showButtons: true,
  smartHide: true,
  hoverOnly: false,
  enabledButtons: { top: true, up: true, down: true, bottom: true },
  scrollPercent: 90,
  separateReadingSpeed: false,
  scrollPercentReading: 90
};
var PageScrollPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    /**
     * One button container per Markdown pane (leaf), living inside that pane's
     * content element. This gives every split/tab its own buttons and keeps them
     * within the editor area (no sidebar overlap, works in pop-out windows).
     */
    this.containers = /* @__PURE__ */ new Map();
    // --- Caret jump-list state (issue #1) ---
    /** Recorded jump-origin positions, oldest → newest. */
    this.caretHistory = [];
    /** Pointer into caretHistory while navigating; -1 means "at the live cursor". */
    this.caretIndex = -1;
    /** The most recent cursor position seen (to detect jumps). */
    this.lastCaret = null;
    /** Live position captured when navigation starts, so forward can return to it. */
    this.caretLive = null;
    /** Set while we move the cursor ourselves, so it isn't recorded as a jump. */
    this.suppressCaretRecord = false;
  }
  async onload() {
    await this.loadSettings();
    for (const def of BUTTON_DEFS) {
      this.addCommand({
        id: `page-scroll-${def.mode}`,
        name: def.label,
        // No default hotkeys — bind your own in Settings → Hotkeys.
        callback: () => this.scroll(def.mode)
      });
    }
    this.addCommand({
      id: "caret-jump-back",
      name: "Jump to previous cursor position",
      callback: () => this.jumpCaret(-1)
    });
    this.addCommand({
      id: "caret-jump-forward",
      name: "Jump to next cursor position",
      callback: () => this.jumpCaret(1)
    });
    this.registerEditorExtension([
      import_view.EditorView.updateListener.of((update) => this.handleCaretUpdate(update))
    ]);
    this.addSettingTab(new PageScrollSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => this.refresh());
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.refresh())
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.refresh())
    );
    this.registerEvent(
      this.app.workspace.on("window-open", () => this.refresh())
    );
    this.registerEvent(
      this.app.workspace.on("window-close", () => this.refresh())
    );
    this.registerEvent(
      this.app.workspace.on("resize", () => this.updateVisibility())
    );
  }
  onunload() {
    for (const container of this.containers.values())
      container.remove();
    this.containers.clear();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    this.settings.enabledButtons = Object.assign(
      {},
      DEFAULT_SETTINGS.enabledButtons,
      data == null ? void 0 : data.enabledButtons
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.renderAll();
  }
  // --- Per-pane containers --------------------------------------------------
  /**
   * Reconcile containers with the current set of Markdown panes: add a button
   * stack to each Markdown leaf (any window/split), drop stacks for panes that
   * are gone or no longer Markdown, then refresh visibility.
   */
  refresh() {
    const seen = /* @__PURE__ */ new Set();
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view instanceof import_obsidian.MarkdownView) {
        seen.add(leaf);
        if (!this.containers.has(leaf))
          this.createContainer(leaf);
      }
    });
    for (const [leaf, container] of this.containers) {
      if (!seen.has(leaf)) {
        container.remove();
        this.containers.delete(leaf);
      }
    }
    this.updateVisibility();
  }
  createContainer(leaf) {
    const view = leaf.view;
    const container = view.contentEl.createDiv({ cls: "pagescroll-container" });
    this.containers.set(leaf, container);
    this.renderButtons(leaf, container);
  }
  // --- Rendering ------------------------------------------------------------
  /** Re-render buttons in every existing container, then refresh visibility. */
  renderAll() {
    for (const [leaf, container] of this.containers) {
      this.renderButtons(leaf, container);
    }
    this.updateVisibility();
  }
  /**
   * How many buttons fit stacked in this pane, and whether an overflow menu is
   * needed. When the pane is too short, buttons fold into a single menu button;
   * at the smallest, that one menu button holds all of them.
   */
  layout(view, enabledCount) {
    const paneH = view.contentEl.clientHeight;
    if (!paneH)
      return { visible: enabledCount, menu: false };
    const SLOT = 34;
    const usable = paneH * 0.85;
    const fit = Math.max(1, Math.floor(usable / SLOT));
    if (fit >= enabledCount)
      return { visible: enabledCount, menu: false };
    return { visible: Math.max(0, fit - 1), menu: true };
  }
  /** Signature of the desired layout, to detect when a re-render is needed. */
  layoutSig(view) {
    const enabled = BUTTON_DEFS.filter((d) => this.settings.enabledButtons[d.mode]);
    if (!this.settings.showButtons || enabled.length === 0)
      return "none";
    const { visible, menu } = this.layout(view, enabled.length);
    return `${visible}${menu ? "m" : ""}`;
  }
  /** (Re)build the buttons inside one pane's container from current settings. */
  renderButtons(leaf, container) {
    container.empty();
    const view = leaf.view;
    container.dataset.sig = view instanceof import_obsidian.MarkdownView ? this.layoutSig(view) : "none";
    if (!this.settings.showButtons || !(view instanceof import_obsidian.MarkdownView))
      return;
    const enabled = BUTTON_DEFS.filter((d) => this.settings.enabledButtons[d.mode]);
    if (enabled.length === 0)
      return;
    const { visible, menu } = this.layout(view, enabled.length);
    const shown = enabled.slice(0, visible);
    const overflow = enabled.slice(visible);
    const scrollFrom = (mode) => {
      if (leaf.view instanceof import_obsidian.MarkdownView)
        this.scroll(mode, leaf.view);
    };
    const keepFocus = (el) => el.addEventListener("mousedown", (e) => e.preventDefault());
    for (const def of shown) {
      const button = container.createEl("button", {
        cls: ["pagescroll-button", "clickable-icon"],
        attr: { "aria-label": def.label, id: `${def.mode}TriskiPageBtn` }
      });
      (0, import_obsidian.setIcon)(button, def.icon);
      keepFocus(button);
      button.onclick = () => scrollFrom(def.mode);
    }
    if (menu && overflow.length) {
      const menuBtn = container.createEl("button", {
        cls: ["pagescroll-button", "clickable-icon"],
        attr: { "aria-label": "Scroll actions" }
      });
      (0, import_obsidian.setIcon)(menuBtn, "ellipsis-vertical");
      keepFocus(menuBtn);
      menuBtn.onclick = (evt) => {
        const m = new import_obsidian.Menu();
        for (const def of overflow) {
          m.addItem(
            (item) => item.setTitle(def.label).setIcon(def.icon).onClick(() => scrollFrom(def.mode))
          );
        }
        m.showAtMouseEvent(evt);
      };
    }
  }
  /** Toggle visibility classes on every pane's container. */
  updateVisibility() {
    for (const [leaf, container] of this.containers) {
      if (!(leaf.view instanceof import_obsidian.MarkdownView))
        continue;
      const view = leaf.view;
      if (container.parentElement !== view.contentEl) {
        view.contentEl.appendChild(container);
      }
      if (container.dataset.sig !== this.layoutSig(view)) {
        this.renderButtons(leaf, container);
      }
      const scrollEl = this.getScrollEl(view);
      const noOverflow = !!scrollEl && scrollEl.scrollHeight <= scrollEl.clientHeight + 1;
      const hidden = !this.settings.showButtons || scrollEl == null || this.settings.smartHide && noOverflow;
      container.toggleClass("pagescroll-hidden", hidden);
      container.toggleClass(
        "pagescroll-hover-only",
        this.settings.showButtons && this.settings.hoverOnly
      );
    }
  }
  // --- Scrolling ------------------------------------------------------------
  /** Resolve the scrollable element for a Markdown view. */
  getScrollEl(view) {
    var _a, _b, _c, _d;
    const internal = view;
    const el = view.getMode() === "preview" ? (_b = (_a = internal.previewMode) == null ? void 0 : _a.renderer) == null ? void 0 : _b.previewEl : (_d = (_c = internal.editMode) == null ? void 0 : _c.cm) == null ? void 0 : _d.scrollDOM;
    return el != null ? el : null;
  }
  /** Page up/down distance (px) for a view, honoring the speed settings. */
  pageDistance(view, scrollEl) {
    const reading = view.getMode() === "preview";
    const percent = this.settings.separateReadingSpeed && reading ? this.settings.scrollPercentReading : this.settings.scrollPercent;
    return scrollEl.clientHeight * (percent / 100);
  }
  /** Scroll a Markdown pane (defaults to the active one, for commands). */
  scroll(mode, view) {
    const v = view != null ? view : this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!v)
      return;
    const scrollEl = this.getScrollEl(v);
    if (!scrollEl)
      return;
    const page = this.pageDistance(v, scrollEl);
    switch (mode) {
      case "up":
        scrollEl.scrollBy(0, -page);
        break;
      case "down":
        scrollEl.scrollBy(0, page);
        break;
      case "top":
        scrollEl.scroll(0, 0);
        break;
      case "bottom":
        this.scrollToEnd(scrollEl);
        break;
    }
  }
  /**
   * Scroll to the true bottom, re-checking over the next few frames. In reading
   * mode, embeds/images render lazily and grow scrollHeight *after* the initial
   * scroll, which would otherwise leave us stuck partway (issue #2). Keep
   * nudging to the new bottom until it settles or we run out of attempts.
   */
  scrollToEnd(el, attempts = 12) {
    var _a;
    el.scroll(0, el.scrollHeight);
    if (attempts <= 0)
      return;
    const win = (_a = el.ownerDocument.defaultView) != null ? _a : window;
    win.requestAnimationFrame(() => {
      if (Math.ceil(el.scrollTop + el.clientHeight) < el.scrollHeight) {
        this.scrollToEnd(el, attempts - 1);
      }
    });
  }
  // --- Caret jump-list (issue #1) -------------------------------------------
  /** CM update listener: notice large cursor jumps and record their origin. */
  handleCaretUpdate(update) {
    var _a;
    if (!update.selectionSet || this.suppressCaretRecord)
      return;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    const file = (_a = view == null ? void 0 : view.file) == null ? void 0 : _a.path;
    if (!file)
      return;
    const head = update.state.selection.main.head;
    const lineObj = update.state.doc.lineAt(head);
    const pos = {
      file,
      line: lineObj.number - 1,
      ch: head - lineObj.from
    };
    const prev = this.lastCaret;
    this.lastCaret = pos;
    if (!prev)
      return;
    const jumped = prev.file !== pos.file || Math.abs(prev.line - pos.line) >= CARET_JUMP_THRESHOLD;
    if (!jumped)
      return;
    if (this.caretIndex !== -1) {
      this.caretHistory = this.caretHistory.slice(0, this.caretIndex + 1);
      this.caretIndex = -1;
    }
    this.caretLive = null;
    this.caretHistory.push(prev);
    if (this.caretHistory.length > MAX_CARET_HISTORY)
      this.caretHistory.shift();
  }
  /** Navigate the caret jump-list: dir = -1 (back) or +1 (forward). */
  jumpCaret(dir) {
    if (this.caretHistory.length === 0)
      return;
    if (dir === -1) {
      if (this.caretIndex === -1) {
        this.caretLive = this.lastCaret;
        this.caretIndex = this.caretHistory.length - 1;
      } else if (this.caretIndex > 0) {
        this.caretIndex--;
      } else {
        return;
      }
      this.applyCaret(this.caretHistory[this.caretIndex]);
      return;
    }
    if (this.caretIndex === -1)
      return;
    if (this.caretIndex < this.caretHistory.length - 1) {
      this.caretIndex++;
      this.applyCaret(this.caretHistory[this.caretIndex]);
    } else {
      this.caretIndex = -1;
      if (this.caretLive)
        this.applyCaret(this.caretLive);
    }
  }
  /** Move the cursor to a remembered position (opening the file if needed). */
  async applyCaret(pos) {
    var _a, _b, _c;
    this.suppressCaretRecord = true;
    try {
      let view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!view || ((_a = view.file) == null ? void 0 : _a.path) !== pos.file) {
        const file = this.app.vault.getAbstractFileByPath(pos.file);
        if (file instanceof import_obsidian.TFile) {
          await this.app.workspace.getLeaf(false).openFile(file);
          view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        }
      }
      const editor = view == null ? void 0 : view.editor;
      if (!editor)
        return;
      const line = Math.min(pos.line, editor.lineCount() - 1);
      const ch = Math.min(pos.ch, (_c = (_b = editor.getLine(line)) == null ? void 0 : _b.length) != null ? _c : 0);
      editor.setCursor({ line, ch });
      editor.scrollIntoView({ from: { line, ch }, to: { line, ch } }, true);
      editor.focus();
      this.lastCaret = { file: pos.file, line, ch };
    } finally {
      window.setTimeout(() => this.suppressCaretRecord = false, 50);
    }
  }
};
var PageScrollSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Show scroll buttons").setDesc(
      "Display the on-screen page-scroll buttons. Turn this off to use only the commands/hotkeys (the buttons can overlap UI from other plugins)."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showButtons).onChange(async (value) => {
        this.plugin.settings.showButtons = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Smart hide").setDesc(
      "Also hide the buttons when the current note is short enough that there's nothing to scroll. (Non-editor panes \u2014 e.g. other plugins' views \u2014 always hide.)"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.smartHide).onChange(async (value) => {
        this.plugin.settings.smartHide = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Visible on hover only").setDesc(
      "Keep the buttons faded out until you hover over them, so they stay unobtrusive."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.hoverOnly).onChange(async (value) => {
        this.plugin.settings.hoverOnly = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Scroll distance").setHeading();
    new import_obsidian.Setting(containerEl).setName("Page up/down distance").setDesc("How far a page up/down scrolls, as a percentage of the visible height.").addSlider(
      (slider) => slider.setLimits(20, 100, 5).setValue(this.plugin.settings.scrollPercent).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.scrollPercent = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Separate distance in Reading view").setDesc("Use a different page up/down distance when viewing in Reading mode.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.separateReadingSpeed).onChange(async (value) => {
        this.plugin.settings.separateReadingSpeed = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.separateReadingSpeed) {
      new import_obsidian.Setting(containerEl).setName("Reading view distance").setDesc("Page up/down distance used in Reading mode.").addSlider(
        (slider) => slider.setLimits(20, 100, 5).setValue(this.plugin.settings.scrollPercentReading).setDynamicTooltip().onChange(async (value) => {
          this.plugin.settings.scrollPercentReading = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Visible buttons").setHeading();
    containerEl.createEl("p", {
      text: "Choose which buttons appear on screen. Commands and hotkeys stay available regardless.",
      cls: "setting-item-description"
    });
    for (const def of BUTTON_DEFS) {
      new import_obsidian.Setting(containerEl).setName(def.label).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.enabledButtons[def.mode]).onChange(async (value) => {
          this.plugin.settings.enabledButtons[def.mode] = value;
          await this.plugin.saveSettings();
        })
      );
    }
  }
};
